# Generated by Django 3.0.7 on 2020-06-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='secret',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
