# Generated by Django 3.0.7 on 2020-06-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='secret',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=10),
        ),
    ]
