# Generated by Django 3.0.7 on 2020-06-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200617_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('normal', 'Normal')], default='normal', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='step',
            field=models.CharField(choices=[('zero', 'Zero'), ('one', 'One'), ('two', 'Two'), ('third', 'Third')], default='one', max_length=6),
        ),
    ]
